CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    family_group_id BIGINT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    dni VARCHAR(20) NOT NULL,
    phone VARCHAR(30),
    email VARCHAR(150),
    joined_at DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_member_club_dni UNIQUE (club_id, dni),
    CONSTRAINT ck_member_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
