CREATE TABLE family_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    name VARCHAR(150),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_family_group_club_id ON family_group(club_id);
