CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    paid_by_member_id BIGINT,
    amount NUMERIC(10, 2) NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    period_covered DATE NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    recorded_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_payment_member FOREIGN KEY (member_id) REFERENCES member(id),
    CONSTRAINT fk_payment_paid_by_member FOREIGN KEY (paid_by_member_id) REFERENCES member(id),
    CONSTRAINT fk_payment_recorded_by_user FOREIGN KEY (recorded_by_user_id) REFERENCES user_account(id),
    CONSTRAINT ck_payment_method CHECK (payment_method IN ('CASH', 'TRANSFER', 'OTHER')),
    CONSTRAINT ck_payment_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_payment_member_id_period_covered ON payment(member_id, period_covered);
